# Generated by Django 2.0.5 on 2018-07-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsappliedjobs',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
