# Generated by Django 2.0.5 on 2018-07-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojp', '0002_jsappliedjobs_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsappliedjobs',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
