# Generated by Django 2.0.5 on 2018-07-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojp', '0003_jsappliedjobs_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsappliedjobs',
            name='notes',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jsappliedjobs',
            name='reason',
            field=models.TextField(default='', max_length=100),
        ),
    ]
