# Generated by Django 2.0.5 on 2018-07-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojp', '0005_auto_20180726_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerdetails',
            name='dp',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='jobseekerdetails',
            name='resume',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='jpdetails',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
    ]
